insert into state (iso3, name) values ('ABW' 'Aruba');
insert into state (iso3, name) values ('AFG', 'Afghanistan');
insert into state (iso3, name) values ('AGO', 'Angola');
insert into state (iso3, name) values ('AIA', 'Anguilla');
insert into state (iso3, name) values ('ALA', 'Åland Islands');
insert into state (iso3, name) values ('ALB', 'Albania');
insert into state (iso3, name) values ('AND', 'Andorra');
insert into state (iso3, name) values ('ANT', 'Netherlands Antilles');
insert into state (iso3, name) values ('ARE', 'United Arab Emirates');
insert into state (iso3, name) values ('ARG', 'Argentina');
insert into state (iso3, name) values ('ARM', 'Armenia');
insert into state (iso3, name) values ('ASM', 'American Samoa');
insert into state (iso3, name) values ('ATA', 'Antarctica');
insert into state (iso3, name) values ('ATF', 'French Southern Territories');
insert into state (iso3, name) values ('ATG', 'Antigua and Barbuda');
insert into state (iso3, name) values ('AUS', 'Australia');
insert into state (iso3, name) values ('AUT', 'Austria');
insert into state (iso3, name) values ('AZE', 'Azerbaijan');
insert into state (iso3, name) values ('BDI', 'Burundi');
insert into state (iso3, name) values ('BEL', 'Belgium');
insert into state (iso3, name) values ('BEN', 'Benin');
insert into state (iso3, name) values ('BFA', 'Burkina Faso');
insert into state (iso3, name) values ('BGD', 'Bangladesh');
insert into state (iso3, name) values ('BGR', 'Bulgaria');
insert into state (iso3, name) values ('BHR', 'Bahrain');
insert into state (iso3, name) values ('BHS', 'Bahamas');
insert into state (iso3, name) values ('BIH', 'Bosnia and Herzegovina');
insert into state (iso3, name) values ('BLM', 'Saint Barthélemy');
insert into state (iso3, name) values ('BLR', 'Belarus');
insert into state (iso3, name) values ('BLZ', 'Belize');
insert into state (iso3, name) values ('BMU', 'Bermuda');
insert into state (iso3, name) values ('BOL', 'Bolivia, Plurinational State of');
insert into state (iso3, name) values ('BRA', 'Brazil');
insert into state (iso3, name) values ('BRB', 'Barbados');
insert into state (iso3, name) values ('BRN', 'Brunei Darussalam');
insert into state (iso3, name) values ('BTN', 'Bhutan');
insert into state (iso3, name) values ('BVT', 'Bouvet Island');
insert into state (iso3, name) values ('BWA', 'Botswana');
insert into state (iso3, name) values ('CAF', 'Central African Republic');
insert into state (iso3, name) values ('CAN', 'Canada');
insert into state (iso3, name) values ('CCK', 'Cocos (Keeling) Islands');
insert into state (iso3, name) values ('CHE', 'Switzerland');
insert into state (iso3, name) values ('CHL', 'Chile');
insert into state (iso3, name) values ('CHN', 'China');
insert into state (iso3, name) values ('CIV', 'Côte d''Ivoire');
insert into state (iso3, name) values ('CMR', 'Cameroon');
insert into state (iso3, name) values ('COD', 'Congo, the Democratic Republic of the');
insert into state (iso3, name) values ('COG', 'Congo');
insert into state (iso3, name) values ('COK', 'Cook Islands');
insert into state (iso3, name) values ('COL', 'Colombia');
insert into state (iso3, name) values ('COM', 'Comoros');
insert into state (iso3, name) values ('CPV', 'Cape Verde');
insert into state (iso3, name) values ('CRI', 'Costa Rica');
insert into state (iso3, name) values ('CUB', 'Cuba');
insert into state (iso3, name) values ('CXR', 'Christmas Island');
insert into state (iso3, name) values ('CYM', 'Cayman Islands');
insert into state (iso3, name) values ('CYP', 'Cyprus');
insert into state (iso3, name) values ('CZE', 'Czech Republic');
insert into state (iso3, name) values ('DEU', 'Germany');
insert into state (iso3, name) values ('DJI', 'Djibouti');
insert into state (iso3, name) values ('DMA', 'Dominica');
insert into state (iso3, name) values ('DNK', 'Denmark');
insert into state (iso3, name) values ('DOM', 'Dominican Republic');
insert into state (iso3, name) values ('DZA', 'Algeria');
insert into state (iso3, name) values ('ECU', 'Ecuador');
insert into state (iso3, name) values ('EGY', 'Egypt');
insert into state (iso3, name) values ('ERI', 'Eritrea');
insert into state (iso3, name) values ('ESH', 'Western Sahara');
insert into state (iso3, name) values ('ESP', 'Spain');
insert into state (iso3, name) values ('EST', 'Estonia');
insert into state (iso3, name) values ('ETH', 'Ethiopia');
insert into state (iso3, name) values ('FIN', 'Finland');
insert into state (iso3, name) values ('FJI', 'Fiji');
insert into state (iso3, name) values ('FLK', 'Falkland Islands (Malvinas)');
insert into state (iso3, name) values ('FRA', 'France');
insert into state (iso3, name) values ('FRO', 'Faroe Islands');
insert into state (iso3, name) values ('FSM', 'Micronesia, Federated States of');
insert into state (iso3, name) values ('GAB', 'Gabon');
insert into state (iso3, name) values ('GBR', 'United Kingdom');
insert into state (iso3, name) values ('GEO', 'Georgia');
insert into state (iso3, name) values ('GGY', 'Guernsey');
insert into state (iso3, name) values ('GHA', 'Ghana');
insert into state (iso3, name) values ('GIB', 'Gibraltar');
insert into state (iso3, name) values ('GIN', 'Guinea');
insert into state (iso3, name) values ('GLP', 'Guadeloupe');
insert into state (iso3, name) values ('GMB', 'Gambia');
insert into state (iso3, name) values ('GNB', 'Guinea-Bissau');
insert into state (iso3, name) values ('GNQ', 'Equatorial Guinea');
insert into state (iso3, name) values ('GRC', 'Greece');
insert into state (iso3, name) values ('GRD', 'Grenada');
insert into state (iso3, name) values ('GRL', 'Greenland');
insert into state (iso3, name) values ('GTM', 'Guatemala');
insert into state (iso3, name) values ('GUF', 'French Guiana');
insert into state (iso3, name) values ('GUM', 'Guam');
insert into state (iso3, name) values ('GUY', 'Guyana');
insert into state (iso3, name) values ('HKG', 'Hong Kong');
insert into state (iso3, name) values ('HMD', 'Heard Island and McDonald Islands');
insert into state (iso3, name) values ('HND', 'Honduras');
insert into state (iso3, name) values ('HRV', 'Croatia');
insert into state (iso3, name) values ('HTI', 'Haiti');
insert into state (iso3, name) values ('HUN', 'Hungary');
insert into state (iso3, name) values ('IDN', 'Indonesia');
insert into state (iso3, name) values ('IMN', 'Isle of Man');
insert into state (iso3, name) values ('IND', 'India');
insert into state (iso3, name) values ('IOT', 'British Indian Ocean Territory');
insert into state (iso3, name) values ('IRL', 'Ireland');
insert into state (iso3, name) values ('IRN', 'Iran, Islamic Republic of');
insert into state (iso3, name) values ('IRQ', 'Iraq');
insert into state (iso3, name) values ('ISL', 'Iceland');
insert into state (iso3, name) values ('ISR', 'Israel');
insert into state (iso3, name) values ('ITA', 'Italy');
insert into state (iso3, name) values ('JAM', 'Jamaica');
insert into state (iso3, name) values ('JEY', 'Jersey');
insert into state (iso3, name) values ('JOR', 'Jordan');
insert into state (iso3, name) values ('JPN', 'Japan');
insert into state (iso3, name) values ('KAZ', 'Kazakhstan');
insert into state (iso3, name) values ('KEN', 'Kenya');
insert into state (iso3, name) values ('KGZ', 'Kyrgyzstan');
insert into state (iso3, name) values ('KHM', 'Cambodia');
insert into state (iso3, name) values ('KIR', 'Kiribati');
insert into state (iso3, name) values ('KNA', 'Saint Kitts and Nevis');
insert into state (iso3, name) values ('KOR', 'Korea, Republic of');
insert into state (iso3, name) values ('KWT', 'Kuwait');
insert into state (iso3, name) values ('LAO', 'Lao People''s Democratic Republic');
insert into state (iso3, name) values ('LBN', 'Lebanon');
insert into state (iso3, name) values ('LBR', 'Liberia');
insert into state (iso3, name) values ('LBY', 'Libyan Arab Jamahiriya');
insert into state (iso3, name) values ('LCA', 'Saint Lucia');
insert into state (iso3, name) values ('LIE', 'Liechtenstein');
insert into state (iso3, name) values ('LKA', 'Sri Lanka');
insert into state (iso3, name) values ('LSO', 'Lesotho');
insert into state (iso3, name) values ('LTU', 'Lithuania');
insert into state (iso3, name) values ('LUX', 'Luxembourg');
insert into state (iso3, name) values ('LVA', 'Latvia');
insert into state (iso3, name) values ('MAC', 'Macao');
insert into state (iso3, name) values ('MAF', 'Saint Martin (French part)');
insert into state (iso3, name) values ('MAR', 'Morocco');
insert into state (iso3, name) values ('MCO', 'Monaco');
insert into state (iso3, name) values ('MDA', 'Moldova, Republic of');
insert into state (iso3, name) values ('MDG', 'Madagascar');
insert into state (iso3, name) values ('MDV', 'Maldives');
insert into state (iso3, name) values ('MEX', 'Mexico');
insert into state (iso3, name) values ('MHL', 'Marshall Islands');
insert into state (iso3, name) values ('MKD', 'Macedonia, the former Yugoslav Republic of');
insert into state (iso3, name) values ('MLI', 'Mali');
insert into state (iso3, name) values ('MLT', 'Malta');
insert into state (iso3, name) values ('MMR', 'Myanmar');
insert into state (iso3, name) values ('MNE', 'Montenegro');
insert into state (iso3, name) values ('MNG', 'Mongolia');
insert into state (iso3, name) values ('MNP', 'Northern Mariana Islands');
insert into state (iso3, name) values ('MOZ', 'Mozambique');
insert into state (iso3, name) values ('MRT', 'Mauritania');
insert into state (iso3, name) values ('MSR', 'Montserrat');
insert into state (iso3, name) values ('MTQ', 'Martinique');
insert into state (iso3, name) values ('MUS', 'Mauritius');
insert into state (iso3, name) values ('MWI', 'Malawi');
insert into state (iso3, name) values ('MYS', 'Malaysia');
insert into state (iso3, name) values ('MYT', 'Mayotte');
insert into state (iso3, name) values ('NAM', 'Namibia');
insert into state (iso3, name) values ('NCL', 'New Caledonia');
insert into state (iso3, name) values ('NER', 'Niger');
insert into state (iso3, name) values ('NFK', 'Norfolk Island');
insert into state (iso3, name) values ('NGA', 'Nigeria');
insert into state (iso3, name) values ('NIC', 'Nicaragua');
insert into state (iso3, name) values ('NIU', 'Niue');
insert into state (iso3, name) values ('NLD', 'Netherlands');
insert into state (iso3, name) values ('NOR', 'Norway');
insert into state (iso3, name) values ('NPL', 'Nepal');
insert into state (iso3, name) values ('NRU', 'Nauru');
insert into state (iso3, name) values ('NZL', 'New Zealand');
insert into state (iso3, name) values ('OMN', 'Oman');
insert into state (iso3, name) values ('PAK', 'Pakistan');
insert into state (iso3, name) values ('PAN', 'Panama');
insert into state (iso3, name) values ('PCN', 'Pitcairn');
insert into state (iso3, name) values ('PER', 'Peru');
insert into state (iso3, name) values ('PHL', 'Philippines');
insert into state (iso3, name) values ('PLW', 'Palau');
insert into state (iso3, name) values ('PNG', 'Papua New Guinea');
insert into state (iso3, name) values ('POL', 'Poland');
insert into state (iso3, name) values ('PRI', 'Puerto Rico');
insert into state (iso3, name) values ('PRK', 'Korea, Democratic People''s Republic of');
insert into state (iso3, name) values ('PRT', 'Portugal');
insert into state (iso3, name) values ('PRY', 'Paraguay');
insert into state (iso3, name) values ('PSE', 'Palestinian Territory, Occupied');
insert into state (iso3, name) values ('PYF', 'French Polynesia');
insert into state (iso3, name) values ('QAT', 'Qatar');
insert into state (iso3, name) values ('REU', 'Réunion');
insert into state (iso3, name) values ('ROU', 'Romania');
insert into state (iso3, name) values ('RUS', 'Russian Federation');
insert into state (iso3, name) values ('RWA', 'Rwanda');
insert into state (iso3, name) values ('SAU', 'Saudi Arabia');
insert into state (iso3, name) values ('SDN', 'Sudan');
insert into state (iso3, name) values ('SEN', 'Senegal');
insert into state (iso3, name) values ('SGP', 'Singapore');
insert into state (iso3, name) values ('SGS', 'South Georgia and the South Sandwich Islands');
insert into state (iso3, name) values ('SHN', 'Saint Helena, Ascension and Tristan da Cunha');
insert into state (iso3, name) values ('SJM', 'Svalbard and Jan Mayen');
insert into state (iso3, name) values ('SLB', 'Solomon Islands');
insert into state (iso3, name) values ('SLE', 'Sierra Leone');
insert into state (iso3, name) values ('SLV', 'El Salvador');
insert into state (iso3, name) values ('SMR', 'San Marino');
insert into state (iso3, name) values ('SOM', 'Somalia');
insert into state (iso3, name) values ('SPM', 'Saint Pierre and Miquelon');
insert into state (iso3, name) values ('SRB', 'Serbia');
insert into state (iso3, name) values ('STP', 'Sao Tome and Principe');
insert into state (iso3, name) values ('SUR', 'Suriname');
insert into state (iso3, name) values ('SVK', 'Slovakia');
insert into state (iso3, name) values ('SVN', 'Slovenia');
insert into state (iso3, name) values ('SWE', 'Sweden');
insert into state (iso3, name) values ('SWZ', 'Swaziland');
insert into state (iso3, name) values ('SYC', 'Seychelles');
insert into state (iso3, name) values ('SYR', 'Syrian Arab Republic');
insert into state (iso3, name) values ('TCA', 'Turks and Caicos Islands');
insert into state (iso3, name) values ('TCD', 'Chad');
insert into state (iso3, name) values ('TGO', 'Togo');
insert into state (iso3, name) values ('THA', 'Thailand');
insert into state (iso3, name) values ('TJK', 'Tajikistan');
insert into state (iso3, name) values ('TKL', 'Tokelau');
insert into state (iso3, name) values ('TKM', 'Turkmenistan');
insert into state (iso3, name) values ('TLS', 'Timor-Leste');
insert into state (iso3, name) values ('TON', 'Tonga');
insert into state (iso3, name) values ('TTO', 'Trinidad and Tobago');
insert into state (iso3, name) values ('TUN', 'Tunisia');
insert into state (iso3, name) values ('TUR', 'Turkey');
insert into state (iso3, name) values ('TUV', 'Tuvalu');
insert into state (iso3, name) values ('TWN', 'Taiwan, Province of China');
insert into state (iso3, name) values ('TZA', 'Tanzania, United Republic of');
insert into state (iso3, name) values ('UGA', 'Uganda');
insert into state (iso3, name) values ('UKR', 'Ukraine');
insert into state (iso3, name) values ('UMI', 'United States Minor Outlying Islands');
insert into state (iso3, name) values ('URY', 'Uruguay');
insert into state (iso3, name) values ('USA', 'United States');
insert into state (iso3, name) values ('UZB', 'Uzbekistan');
insert into state (iso3, name) values ('VAT', 'Holy See (Vatican City State)');
insert into state (iso3, name) values ('VCT', 'Saint Vincent and the Grenadines');
insert into state (iso3, name) values ('VEN', 'Venezuela, Bolivarian Republic of');
insert into state (iso3, name) values ('VGB', 'Virgin Islands, British');
insert into state (iso3, name) values ('VIR', 'Virgin Islands, U.S.');
insert into state (iso3, name) values ('VNM', 'Viet Nam');
insert into state (iso3, name) values ('VUT', 'Vanuatu');
insert into state (iso3, name) values ('WLF', 'Wallis and Futuna');
insert into state (iso3, name) values ('WSM', 'Samoa');
insert into state (iso3, name) values ('YEM', 'Yemen');
insert into state (iso3, name) values ('ZAF', 'South Africa');
insert into state (iso3, name) values ('ZMB', 'Zambia');
insert into state (iso3, name) values ('ZWE', 'Zimbabwe');
